title: nileshkalani
logo: /assets/img/small.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal


I work on Data Science, Machine Learning and Embedded Sysetms.
